import time
name = input("Enter your name to put it in a song!")

print("It was a Friday: I saw a movie, but it wasn\'t very long, so I snuck into another one.")
time.sleep(4)
print("Employees caught me; they through me out into the mall, all in all, it was pretty fun.")
time.sleep(4)
print("But then it happened: I bumped into a random guy, he said \"Excuse me,\" and he tried to walk away.")
time.sleep(5)
print("But I had just had a psychic vision")
time.sleep(3)
print("I said, \"Sir, I don\'t know why, but I know your name.\"")
time.sleep(2)
print("I said,")
time.sleep(1)
print("\"I know, I know, I know your name.\"")
time.sleep(3)
print("\"I know, I know, I know your name.\"")
time.sleep(3)
print("\"I know, I know, I know your name.\"")
time.sleep(3)
print("\"I know, I know your name is..\"")
time.sleep(5)
print("\"Your name is " + name + ".\"")
time.sleep(4)
print("\"Your name is " + name + ".\"")
time.sleep(4)
print("\"Your name is " + name + ", I know...\"")
time.sleep(5)
print("The guy said \"Sorry, my name is Fred.\"")
time.sleep(4)
print("And then he slowly walked away. I never saw that guy again.")
time.sleep(4)
print("Went back to my house to feed my fish which was floating on its back.")
time.sleep(4)
print("So, I gave it to the cat.")
time.sleep(2)
print("When he was finished, I took the bones away.")
time.sleep(3)
print("But right before I reached the garbage something happened in my brain.")
time.sleep(4)
print("Well, I had just had a psychic vision;")
time.sleep(3)
print("I said, \"Cat, I don\'t know why, but I know your name.\"")
time.sleep(2)
print("I said,")
time.sleep(1)
print("\"I know, I know, I know your name.\"")
time.sleep(3)
print("\"I know, I know, I know your name.\"")
time.sleep(3)
print("\"I know, I know, I know your name.\"")
time.sleep(3)
print("\"I know, I know your name is..\"")
time.sleep(3)
print("\"Your name is " + name + ".\"")
time.sleep(3)
print("\"Your name is " + name + ".\"")
time.sleep(3)
print("\"Your name is " + name + ", I know...\"")
time.sleep(4)
print("The cat said nothing, and then threw up onto my freshly shampooed carpet;")
time.sleep(3)
print("I rolled my eyes and walked outside.")
time.sleep(2)
print("It started raining; I ran for shelter in an alleyway that smelled as if an elephant had died.")
time.sleep(5)
print("There was a box there, I looked inside to se a homeless man dressed in rags, bearded and insane.")
time.sleep(5)
print("And suddenly, I had a psychic vision;")
time.sleep(3)
print("I said, \"Sir, I don\'t know why, but I know your name.\"")
time.sleep(2)
print("I said,")
time.sleep(1)
print("\"I know, I know, I know your name.\"")
time.sleep(3)
print("\"I know, I know, I know your name.\"")
time.sleep(3)
print("\"I know, I know, I know your name.\"")
time.sleep(3)
print("\"I know, I know your name is..\"")
time.sleep(3)
print("\"Your name is " + name + ".\"")
time.sleep(3)
print("\"Your name is " + name + ".\"")
time.sleep(3)
print("\"Your name is " + name + ", I know...\"")
time.sleep(4)
print(name + " Marley.")
time.sleep(1)
print(name + " Saget.")
time.sleep(1)
print(name + " Hoffman.")
time.sleep(1)
print(name + " Ross.")
time.sleep(1)
print(name + " DeNiro.")
time.sleep(1)
print("Sponge" + name + " Squarepants.")
time.sleep(3)
print("The homeless man stared. He looked a bit scared")
time.sleep(3)
print("He asked me how I knew his name; I couldn\'t say.")
time.sleep(3)
print("And it was awkward. He fell asleep, and I walked back home in the rain. (In the rain...)")
time.sleep(5)
print("But then it happened: another vision came to me;")
time.sleep(3)
print("Another psychic idea from my dreams.")
time.sleep(3)
print("I knew I had to burn down the supermarket to achieve world peace.")
time.sleep(5)
print("So I did...")
time.sleep(1)
print("🏪🛒🛒 ")
time.sleep(.2)
print("🏪🛒🛒 🔥🔥")
time.sleep(.2)
print("🏪🛒🛒🔥🔥")
time.sleep(.2)
print("🏪🛒🔥🔥")
time.sleep(.2)
print("🏪🔥🔥🌫")
time.sleep(.2)
print("🔥🔥🌫🌫")
time.sleep(0.2)
print("🔥🌫🌫🌫")
time.sleep(0.2)
print("🌫🌫🌫🌫")
time.sleep(1)
print("🌫🌫🌫🌫     🚒")
time.sleep(.2)
print("🌫🌫🌫🌫    🚒")
time.sleep(.2)
print("🌫🌫🌫🌫   🚒")
time.sleep(.2)
print("🌫🌫🌫🌫  🚒")
time.sleep(.2)
print("🌫🌫🌫🌫 🚒")
time.sleep(1)
print("🌫🌫🌫🌫 🚒👨‍🚒")
time.sleep(.2)
print("🌫🌫🌫🌫 🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌫🌫🌫🌫 🚒👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌫🌫🌫🌫 🚒 🧯👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌫🌫🌫🌫 🚒  🧯👩‍🚒 🧯👨‍🚒")
time.sleep(1)
print("🌫🌫🌫🌫 🚒 🧯👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌫🌫🌫🌫 🚒🧯👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌫🌫🌫🌫 🧯👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌫🌫🌫🌫🧯👩‍🚒 🧯👨‍🚒")
time.sleep(1)
print("🌫🌫🌫🌫🌪🧯👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌫🌫🌫🌪🧯👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌫🌫🌪🧯👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌫🌪🧯👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🌪🧯👩‍🚒 🧯👨‍🚒")
time.sleep(.2)
print("🧯👩‍🚒 🧯👨‍🚒")
time.sleep(1)
print("THE END")
time.sleep(1)
print("MADE BY CALEB")
time.sleep(1)
print("2021")